#!/usr/bin/env bash
# A Bash script to transfer a file from client to server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_to_file = $1
server_ip = $2
username = $3
path_to_ssh_key = $4

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$server_ip:~/"

if [ $? -eq 0 ]
then
	echo "$path_to_file file is transferred successfully"
else
	echo "File transfer failed"
fi
