#!/usr/bin/env bash
# Installing Nginx on web server

sudo apt update
sudo apt -y install nginx
sudo ufw "Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx restart
sudo service nginx reload
