#!/usr/bin/env bash
# file contains PID
terminating='rm /var/run/myscript.pid; exit $?'
echo $$ > /var/run/myscript.pid

while true
do
        echo "To infinity and beyond"
        sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminating' SIGTERM
	trap 'terminating' SIGQUIT
done

