#!/usr/bin/env bash
# displays content of a file
while IFS= read -r contents
do
	usrname=$(echo "$contents" | cut -f 1 -d ":")
	pass=$(echo "$contents" | cut -f 2 -d ":")
	uid=$(echo "$contents" | cut -f 3 -d ":")
	gid=$(echo "$contents" | cut -f 4 -d ":")
	uinfo=$(echo "$contents" | cut -f 5 -d ":")
	home=$(echo "$contents" | cut -f 6 -d ":")
	cmdd=$(echo "$contents" | cut -f 7 -d ":")
	echo -n "The user $usrname is part of the $gid gang, "
	echo -n "lives in $home and rides $cmdd. "
	echo -n "$uid's place is protected by the passcode $pass, "
	echo -n "more info about the user here: $uinfo"
done < "/etc/passwd"
