#!/usr/bin/env bash
# displays a text 10 times with hi after 9
j=1
while [ "$j" -le 10 ]
do
	if [ "$j" -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	j=$(( j + 1 ))
done
