#!/usr/bin/env bash
# show number from 1 - 20 with exceptions
j=1
while [ "$j" -le 20 ]
do
	echo "$j"
	case $j in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	j=$(( j + 1 ))
done
